[project]
name = "monitor-arduino-led"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pyserial>=3.5",
    "requests>=2.32.4",
    "uptime-kuma-api>=1.2.1",
]
